### ISSUE TITLE
Gaussian Pulse

### ISSUE THREAD

**Issue by pwinni** [gara613/CMUN_Meas#1]
Hey, thanks for the great work in this package!
Line 74 of tdSpars.m (TimeGating subdirectory) calls the function gaussPulse which does not exist in the package I downloaded. There is a mathworks function 'gauspuls' that seems to work fine in its place, or perhaps you wrote your own function that got omitted from the package. Thought you would like to know.

Anyway, thanks again for the great work!

**Comment by gara613** [comment]
Thanks for reporting this issue, in fact there was a missing file. I'm sorry for the inconvenience. 
Thank you for using this code I hope it has been useful.
